---
language: java
install: true
# java host problematic https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
addons:
  hosts:
    - myshorthost
  hostname: myshorthost
script: $TARGET
jdk:
- oraclejdk8

env:
  matrix:
    - TARGET='mvn test'

notifications:
  email:
    - michael@mosmann.de
    - m.joehren@gmail.com

cache:
  directories:
    - $HOME/.m2/repository
